<a href="https://colab.research.google.com/github/RedEgnival/sem-4/blob/main/I069_SIP_lab_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rusheel Sharma
# I069
# SIP Lab 7

In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,1,2])

In [ ]:
X = np.fft.fft(x)
X

array([ 6.+0.j,  0.+0.j, -2.+0.j,  0.+0.j])

In [ ]:
x_est = np.fft.ifft(x)
x_est

array([ 1.5+0.j,  0. +0.j, -0.5+0.j,  0. +0.j])

Twiddle Factor

In [ ]:
N = 4
W = np.zeros((4,4),dtype = complex)
for n in range (0,N):
  for k in range (0,N):
    real = np.cos(2*np.pi*n*k/N)
    img = -1*(np.sin(2*np.pi*n*k/N))
    W[n,k] = complex(real,img)
W

array([[ 1.0000000e+00-0.0000000e+00j,  1.0000000e+00-0.0000000e+00j,
         1.0000000e+00-0.0000000e+00j,  1.0000000e+00-0.0000000e+00j],
       [ 1.0000000e+00-0.0000000e+00j,  6.1232340e-17-1.0000000e+00j,
        -1.0000000e+00-1.2246468e-16j, -1.8369702e-16+1.0000000e+00j],
       [ 1.0000000e+00-0.0000000e+00j, -1.0000000e+00-1.2246468e-16j,
         1.0000000e+00+2.4492936e-16j, -1.0000000e+00-3.6739404e-16j],
       [ 1.0000000e+00-0.0000000e+00j, -1.8369702e-16+1.0000000e+00j,
        -1.0000000e+00-3.6739404e-16j,  5.5109106e-16-1.0000000e+00j]])

In [ ]:
X1= np.dot(W,np.transpose(x))
print(X)

[ 6.+0.j  0.+0.j -2.+0.j  0.+0.j]


In [ ]:
N=4
W_inv=np.zeros((4,4), dtype=complex)
for n in range(0,N):
  for k in range(0,N):
    real = int(np.cos(2*np.pi*n*k/N))
    imaginary = int(np.sin(2*np.pi*n*k/N))
    W_inv[n,k]=complex(real,imaginary)
print(W_inv)

[[ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
 [ 1.+0.j  0.+1.j -1.+0.j  0.-1.j]
 [ 1.+0.j -1.+0.j  1.+0.j -1.+0.j]
 [ 1.+0.j  0.-1.j -1.+0.j  0.+1.j]]


In [ ]:
N=8
W=np.zeros((8,8),dtype=complex)
for n in range(0,N):
  for k in range(0,N):
    real = np.cos(2*np.pi*n*k/N)
    imaginary = -1*(np.sin(2*np.pi*n*k/N))
    W[n,k]=np.round(complex(real,imaginary))
print(W)

[[ 1.-0.j  1.-0.j  1.-0.j  1.-0.j  1.-0.j  1.-0.j  1.-0.j  1.-0.j]
 [ 1.-0.j  1.-1.j  0.-1.j -1.-1.j -1.-0.j -1.+1.j -0.+1.j  1.+1.j]
 [ 1.-0.j  0.-1.j -1.-0.j -0.+1.j  1.+0.j  0.-1.j -1.-0.j -0.+1.j]
 [ 1.-0.j -1.-1.j -0.+1.j  1.-1.j -1.-0.j  1.+1.j  0.-1.j -1.+1.j]
 [ 1.-0.j -1.-0.j  1.+0.j -1.-0.j  1.+0.j -1.-0.j  1.+0.j -1.-0.j]
 [ 1.-0.j -1.+1.j  0.-1.j  1.+1.j -1.-0.j  1.-1.j -0.+1.j -1.-1.j]
 [ 1.-0.j -0.+1.j -1.-0.j  0.-1.j  1.+0.j -0.+1.j -1.-0.j -0.-1.j]
 [ 1.-0.j  1.+1.j -0.+1.j -1.+1.j -1.-0.j -1.-1.j -0.-1.j  1.-1.j]]


In [ ]:
x2=np.array([1,1,1,1,1,1,0,0])

In [ ]:
X2=np.dot(W,np.transpose(x2))
for i in range(0,7):
  print(X2[i])

X2new=np.fft.fft(x2, axis=-1, norm=None)
for i in range(0,7):
  print(X2new[i])


(6+0j)
(-1-2j)
(1-1j)
(1+0j)
0j
(1+0j)
(1+1j)
(6+0j)
(-0.7071067811865476-1.7071067811865475j)
(1-1j)
(0.7071067811865476+0.2928932188134524j)
0j
(0.7071067811865476-0.2928932188134524j)
(1+1j)
