<a href="https://colab.research.google.com/github/RedEgnival/sem-4/blob/main/I069_SIP_Lab_3b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rusheel Sharma

# I069

# SIP lab 3b



In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

Low Pass Filter


In [ ]:
matrix = np.array(np.random.randint(10, size=(5, 6)))
m,n = matrix.shape

matrix2= []
print(matrix)
for i in range (1,m-1):
  for j in range(1,n-1):
    avg = (matrix[i-1][j-1] + matrix[i-1][j] + matrix[i][j] + matrix[i-1][j+1] + matrix[i][j-1] + matrix[i][j+1] )
    x = np.round(avg/6)
    matrix2.append(x)
print()
matrix2 = np.reshape(matrix2,(3,4))
for i in range (1,m-1):
  for j in range( 1,n-1):
    matrix[i][j] = matrix2[i-1][j-1]
print(matrix)

[[6 6 9 4 7 3]
 [9 2 3 0 0 2]
 [1 4 6 5 0 0]
 [7 7 6 7 5 6]
 [2 0 3 7 7 5]]

[[6 6 9 4 7 3]
 [9 6 4 4 3 2]
 [1 4 3 2 1 0]
 [7 5 6 5 4 6]
 [2 0 3 7 7 5]]


Spatial Domain low pass filtering for variable size mask

In [ ]:
plt.figure(figsize=(8,7))
img = cv2.imread("/content/messi.jpg")
for i in range(1,5):
  b = int(input("Enter the value of mark : "))
  (m,n) = img.shape
  img_gen = np.zeroes([m,n], dtype = int)
  a = b//2
  for j in range(a, m-a):
    for k in range(a, n-a):
      temp = img[j-a:j+a+1,k-1,k+a+1]
      con=np.sum(temp)
      img_gen[j,k] = con // b**2

  plt.subplot(2,3,i)
  plt.title(b)
  plt.imsh